### ISSUE TITLE
Adding parameters to the theme function

### ISSUE THREAD

**Issue by SimardeepKaur** [UBC-MDS/hueniversitypy#35]
In altair, registering the theme with parameters is something which is not documented as of now. I have tried looking for  a couple of solutions and ended up with this. 
https://github.com/altair-viz/altair/issues/840

Let me know if any one finds a solution for this

**Comment by reikookamoto** [comment]
Looks like we won't be passing any argument to `theme_<university>`. For universities with multiple colour palettes, we'll just pick one to create the altair theme.
