### ISSUE TITLE
Workflow for week 3

### ISSUE THREAD

**Issue by reikookamoto** [UBC-MDS/hueniversitypy#51]
- Set up GitHub Actions for Continuous Integration (CI) and Continuous Deployment (CD) with Python @SimardeepKaur 
- Create defensive tests @evelynmoorhouse 
- Add thorough examples (1 plot without theme enabled, 4 plots with different themes enabled) @evelynmoorhouse 
- Communicate branch coverage via codecov.io badge on README @evelynmoorhouse 
- Update documentation using Read the Docs @SimardeepKaur 
- Go over ROpenSci checklist @SimardeepKaur @vermashivam679 
We're each responsible for:
- Examine docstrings of your functions
- Examine whether one-line descriptions of your unit test functions make sense
- Review branch coverage (aim for 90% branch coverage)

**Comment by evelynmoorhouse** [comment]
also :
* add usage for each function in README.md

**Comment by reikookamoto** [comment]
^ Added above
