### ISSUE TITLE
Milestone 2 code feedback 

### ISSUE THREAD

**Issue by andytai7** [UBC-MDS/hueniversitypy#63]
R Repo looks good. Like I had spoken to this group in the lab, please delete the branches for the Python Repo

Python Coding: 
Unused variable:
Undefined variable ‘alt’
Or Unused variable like ‘sourceFont’ ‘axisColor and ‘gridColor’
I think this is because of discrepancies, and tests ran fine even when there were these errors. Mostly occurring in mcgill and Toronto. Should be fixed with the dependencies fixed with continuous integration with poetry.  

Python Tests: 
All of the python tests worked Great job. 

R coding: 
Rcoding looks fine

R tests: 
I think again there is some sort of discrepancies in terms of test for R. No marks will be deducted.

**Comment by reikookamoto** [comment]
@andytai7 Could clarify what you mean by discrepances with respect to the R test functions?
